### ISSUE TITLE
Docker issues

### ISSUE THREAD

**Issue by lxrst** [ComicLib/comiclib#2]
The Docker image contains a lot of large files, which is probably not what you want.

 - ExH dump ([Line 19](https://github.com/ComicLib/comiclib/blob/master/Dockerfile#L19)):
   - This line extracts from /tmp to the working directory, which is included in the final image; resulting in all however many GB being added.
 - 7zip utils ([Line 16](https://github.com/ComicLib/comiclib/blob/master/Dockerfile#L16)):
   - The `7zz` is extracted into `/usr/bin`, which is also included in the final image.

Having read the documentation, I'm assuming you mean for the ExH dump to be included.
I highly recommend a Docker volume for this, as Docker Hub can be quite slow at times and large files increase strain on their servers.

Also, very exciting project! I'll contribute when I find the time.

If you're new to programming / free software, keep going; you'll make great things!

**Comment by URenko** [comment]
The Docker images are designed to provide all features out of the box.

7zip utils, whose size is only several MB, is required for rar or 7z file ([document](https://comiclib.github.io/comiclib/en/supported-formats/#fn:1))

I am not familiar with Docker and it is also not the recommend way. Someone more familiar with it can help improve it.

**Comment by karuboniru** [comment]
I believe the image size issue is (at least partially) addressed by the mentioned PR. 

Though, I did not remove the files you have mentioned, but the image size is stipped by half using some Dockerfile techniques.

**Comment by URenko** [comment]
Should be alleviated in v0.0.5
